In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
train = pd.read_csv('train.csv')
train = train.drop('id', axis=1)
test = pd.read_csv('test.csv')
original = pd.read_csv('original.csv')

TARGET = 'diagnosed_diabetes'

In [3]:
train.sample(5)

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
286190,41,2,91,2.5,6.7,3.6,26.0,0.85,108,73,...,Female,White,Highschool,Middle,Current,Retired,1,1,0,1.0
171399,68,3,25,5.0,7.2,7.1,32.9,0.91,124,82,...,Male,White,Highschool,Middle,Never,Employed,0,0,0,1.0
135247,64,3,90,5.7,6.1,7.6,21.9,0.82,115,66,...,Male,Hispanic,Highschool,Middle,Never,Employed,0,0,0,0.0
219181,58,2,146,8.6,8.8,2.6,23.5,0.83,120,80,...,Male,Other,Highschool,Lower-Middle,Current,Retired,0,1,0,0.0
685171,41,3,64,4.7,7.5,7.1,24.5,0.86,95,71,...,Male,White,Postgraduate,Lower-Middle,Former,Employed,0,0,0,1.0

In [4]:
original.sample(5)

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
9805,29,Female,Black,Graduate,Lower-Middle,Employed,Never,3,7,3.3,...,51,91,135,102,154,10.34,6.17,28.8,Pre-Diabetes,0
41963,51,Male,Black,Graduate,Middle,Employed,Never,1,68,7.4,...,37,113,124,108,163,12.79,6.43,29.1,Type 2,1
44590,21,Male,White,Graduate,Upper-Middle,Retired,Never,2,49,4.4,...,54,80,152,101,126,2.00,5.82,20.7,Pre-Diabetes,0
7724,76,Male,Other,Graduate,Lower-Middle,Student,Never,3,109,6.9,...,56,95,147,112,184,3.81,6.88,32.8,Type 2,1
91550,52,Female,Black,Graduate,Lower-Middle,Employed,Current,4,193,6.3,...,56,79,138,124,165,9.09,6.93,25.2,Type 2,1

In [7]:
set(original.columns) - set(train.columns)

{'diabetes_risk_score',
 'diabetes_stage',
 'glucose_fasting',
 'glucose_postprandial',
 'hba1c',
 'insulin_level'}

In [8]:
set(train.columns) - set(original.columns)

set()

In [5]:
# mutual information
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_selection import mutual_info_classif

X = train.copy()
y = X.pop(TARGET)

for col in X.select_dtypes(['object', 'category']).columns:
    X[col] = LabelEncoder().fit_transform(X[col])

discrete_features = X.dtypes == int

def make_mi_scores(X, y, discrete_features):
    mi_scores = mutual_info_classif(X, y, discrete_features=discrete_features)
    mi_scores = pd.Series(mi_scores, name='MI Scores', index=X.columns)
    mi_scores = mi_scores.sort_values(ascending=False)
    return mi_scores

mi_scores = make_mi_scores(X, y, discrete_features)
mi_scores

physical_activity_minutes_per_week    0.034840
family_history_diabetes               0.025411
age                                   0.014536
waist_to_hip_ratio                    0.009564
triglycerides                         0.008470
bmi                                   0.006317
systolic_bp                           0.006296
ldl_cholesterol                       0.006057
cholesterol_total                     0.004759
sleep_hours_per_day                   0.002878
diet_score                            0.002660
screen_time_hours_per_day             0.001886
hdl_cholesterol                       0.001623
diastolic_bp                          0.000775
heart_rate                            0.000524
hypertension_history                  0.000453
cardiovascular_history                0.000315
alcohol_consumption_per_week          0.000045
ethnicity                             0.000034
education_level                       0.000033
income_level                          0.000031
employment_status                     0.000013
gender                                0.000006
smoking_status                        0.000002
Name: MI Scores, dtype: float64

In [6]:
sns.countplot(data=train, x='employment_status', hue='loan_paid_back')

ValueError: Could not interpret value `loan_paid_back` for `hue`. An entry with this name does not appear in `data`.

In [ ]:
sns.boxplot(data=train, x='loan_paid_back', y='debt_to_income_ratio')

In [ ]:
sns.boxplot(data=train, x='loan_paid_back', y='credit_score')

In [ ]:
# difference between original data set and this competition
print(set(original.columns) - set(train.columns))
print(set(train.columns) - set(original.columns))

In [ ]:
original.drop(columns=['num_of_delinquencies', 'installment', 'delinquency_history', 'monthly_income', 'current_balance', 'total_credit_limit', 'public_records', 'age', 'num_of_open_accounts', 'loan_term'])

In [ ]:
# test for class imbalance
print(f"train target mean = {train['loan_paid_back'].mean()}")